node('linux') {
    echo "Running ${env.BUILD_ID} on ${env.JENKINS_URL}"
    checkout scm

    AWS_ACCESS_KEY_ID     = credentials('jenkins-aws-secret-key-id')
    AWS_SECRET_ACCESS_KEY = credentials('jenkins-aws-secret-access-key')

    def username = 'Jenkins'
    echo "I said, Hello Mr. ${username}"

    stage('Build') {
        echo 'Building....'

//             withEnv(["PATH+MAVEN=${tool 'M3'}/bin"]) {
//                 sh 'mvn -B verify'
//             }

    }
    stage('Test') {
        echo 'Testing....'

            node('linux') {
            }
            node('windows') {
            }

    parallel linux: {
        node('linux') {
        }
    },
    windows: {
        node('windows') {
        }
    }

    }
    stage('Deploy') {

    docker.image('mysql:5').withRun('-e "MYSQL_ROOT_PASSWORD=my-secret-pw" -p 3306:3306') { c ->
        /* Wait until mysql service is up */
        sh 'while ! mysqladmin ping -h0.0.0.0 --silent; do sleep 1; done'
        /* Run some tests which require MySQL */
        sh 'make check'
    }

        docker.image('node:14-alpine').inside {
            stage('Test') {
                sh 'node --version'
            }
        }


        echo 'Deploying....'
        if (currentBuild.result == null || currentBuild.result == 'SUCCESS') {
            echo 'Success....'
        }
    }



}